deviceManagementObjAWS:
  type: object
  properties:
    allowUsersToManageDevices:
      type: boolean
      example: true
    managementInterfaces:
      type: array
      items:
        type: object
        required:
          - managementType
          - type
          - authType
        properties:
          managementType:
            type: string
            enum:
              - primary
              - secondary
          enabled:
            type: boolean
            example: true
          type:
            type: string
            enum: [Telnet, SSH, RDP, VNC, HTTP, HTTPS]
          authType:
            type: string
            example: password
          username:
            type: string
          password:
            type: string
          password_2:
            type: string
          privateKey:
            type: string
          passphrase:
            type: string
          supportsSFTP:
            type: boolean
            example: true
